#!/bin/sh

set -e

DELUGE_WEB_USER="debian-squall-web"
DELUGE_WEB_GROUP="debian-squall-web"

case "${1}" in
	purge)
		rm -f /var/log/squall-web/*
		rm -rf /var/lib/squall-web

		userdel ${DELUGE_WEB_USER} > /dev/null 2>&1 || true
		groupdel ${DELUGE_WEB_GROUP} > /dev/null 2>&1 || true
		;;

	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
		;;

	*)
		echo "postrm called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
